# Generated by Django 2.2.10 on 2020-02-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorquestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorquestionresponse',
            options={'ordering': ['mentorQuestion', 'schoolAdministrator'], 'verbose_name': 'Mentor Question Response'},
        ),
    ]
