# Generated by Django 2.2.8 on 2020-02-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('mentorquestions', '0002_mentorquestionresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorquestionresponse',
            unique_together={('mentorQuestion', 'mentor')},
        ),
    ]
