# Generated by Django 3.0.7 on 2020-10-10 01:24

import common.fields
import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rcjaRegistration.storageBackends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_auto_20201010_1224'),
        ('eventfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorEventFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('fileUpload', common.fields.UUIDFileField(storage=rcjaRegistration.storageBackends.PrivateMediaStorage(), upload_to=common.fields.UUIDFIeld.generateUUIDFilename, verbose_name='File')),
                ('originalFileName', models.CharField(editable=False, max_length=300, verbose_name='Original filename')),
                ('eventAttendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.BaseEventAttendance', verbose_name='Team/ attendee')),
                ('uploadedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Mentor Event File',
            },
            bases=(common.models.SaveDeleteMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='MentorEventAttendanceFile',
        ),
    ]
