# Generated by Django 3.0.7 on 2020-10-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20201010_1259'),
        ('eventfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAvailableFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('uploadDeadline', models.DateTimeField(verbose_name='Upload deadline')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
                ('fileType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventfiles.MentorEventFileType', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Event Available File Type',
                'unique_together': {('event', 'fileType')},
            },
        ),
    ]
