# Generated by Django 3.0.7 on 2020-10-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventfiles', '0002_eventavailablefiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventavailablefiletype',
            name='uploadDeadline',
            field=models.DateField(verbose_name='Upload deadline'),
        ),
    ]
