FROM tiangolo/meinheld-gunicorn:python3.7
ENV PATH="${PATH}:/app"
ENV APP_MODULE="rcjaRegistration.wsgi:application"

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
COPY rcjaRegistration /app
