version: '3'

services:
  web:
    environment:
      - DATABASE_URL=postgres://rcjaRegistration:abc123@db/rcjaRegistration
      - DEV_SETTINGS=true
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rcjaRegistration
      - POSTGRES_USER=rcjaRegistration
      - POSTGRES_PASSWORD=abc123

volumes:
  postgres_data:
