# Generated by Django 2.2.10 on 2020-02-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forceDetailsUpdate',
            field=models.BooleanField(default=False, verbose_name='Force details update'),
        ),
        migrations.AddField(
            model_name='user',
            name='forcePasswordChange',
            field=models.BooleanField(default=False, verbose_name='Force password change'),
        ),
    ]
