# Generated by Django 2.2.8 on 2020-02-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile number'),
        ),
    ]
