# Generated by Django 3.0.3 on 2020-05-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20200504_2102'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='homeState',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeRegistration': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='Home state'),
        ),
    ]
