# Generated by Django 2.2.8 on 2020-02-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20200221_2243'),
        ('users', '0002_auto_20200221_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='homeRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.Region', verbose_name='Home region'),
        ),
        migrations.AddField(
            model_name='user',
            name='homeState',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='Home state'),
        ),
    ]
