# Generated by Django 3.0.7 on 2020-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200504_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='independentSelected',
            field=models.BooleanField(default=False, editable=False, verbose_name='Independent selected'),
        ),
    ]
