# Generated by Django 4.2.4 on 2023-09-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_remove_state_typeregistration_state_typecompetition_and_more'),
        ('users', '0003_auto_20210518_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='homeState',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeUserRegistration': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.state', verbose_name='Home state'),
        ),
    ]
