# Generated by Django 2.2.10 on 2020-02-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200224_0021'),
        ('users', '0004_auto_20200221_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentlySelectedSchool',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.School', verbose_name='Currently selected school'),
        ),
    ]
