# Generated by Django 4.2.4 on 2023-09-03 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_division_state_alter_event_state_and_more'),
        ('regions', '0007_remove_state_typeregistration_state_typecompetition_and_more'),
        ('users', '0004_alter_user_homestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentlySelectedAdminState',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.state', verbose_name='Currently selected admin state'),
        ),
        migrations.AddField(
            model_name='user',
            name='currentlySelectedAdminYear',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.year', verbose_name='Currently selected admin year'),
        ),
    ]
