# Generated by Django 4.2.4 on 2023-09-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_currentlyselectedadminstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminChangelogVersionShown',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Changelog version shown'),
        ),
    ]
