# Generated by Django 4.2.4 on 2023-09-08 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_adminchangelogversionshown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_()+ and space.", regex='^[0-9a-zA-Z \\-\\_\\(\\)\\+]*$')], verbose_name='Mobile number'),
        ),
    ]
