# Generated by Django 2.2.10 on 2020-02-26 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20200226_1204'),
        ('schools', '0002_auto_20200226_1204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('invoiceNumber', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Invoice number')),
                ('invoicedDate', models.DateField(blank=True, null=True, verbose_name='Invoiced date')),
                ('purchaseOrderNumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Purchase order number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('campus', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.Campus', verbose_name='Campus')),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='events.Event', verbose_name='Event')),
                ('invoiceToUser', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Invoice to')),
                ('school', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.School', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Invoice',
                'ordering': ['-invoiceNumber'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceGlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('invoiceFromName', models.CharField(max_length=50, verbose_name='Invoice from name')),
                ('invoiceFromDetails', models.TextField(verbose_name='Invoice from details')),
                ('invoiceFooterMessage', models.TextField(verbose_name='Invoice footer message')),
            ],
            options={
                'verbose_name': 'Invoice settings',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('amountPaid', models.PositiveIntegerField(verbose_name='Amount paid')),
                ('datePaid', models.DateField(verbose_name='Date paid')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.Invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'ordering': ['invoice', 'datePaid'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(campus=None), fields=('event', 'school'), name='event_school'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(school=None), fields=('event', 'invoiceToUser'), name='event_user'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('event', 'school', 'campus'), name='event_school_campus'),
        ),
    ]
