# Generated by Django 2.2.8 on 2020-02-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('events', '0002_auto_20200221_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('purchaseOrderNumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Purchase order number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event', verbose_name='Event')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.School', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Invoice',
                'ordering': ['event', 'school'],
                'unique_together': {('school', 'event')},
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('amountPaid', models.PositiveIntegerField(verbose_name='Amount paid')),
                ('datePaid', models.DateField(verbose_name='Date paid')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.Invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'ordering': ['invoice', 'datePaid'],
            },
        ),
    ]
