# Generated by Django 2.2.10 on 2020-02-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('schools', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='campus',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.Campus', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='events.Event', verbose_name='Event'),
        ),
    ]
