# Generated by Django 2.2.10 on 2020-02-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_auto_20200226_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceToUser',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Invoice to'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.School', verbose_name='School'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(campus=None), fields=('event', 'school'), name='event_school'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(school=None), fields=('event', 'invoiceToUser'), name='event_user'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('event', 'school', 'campus'), name='event_school_campus'),
        ),
    ]
