# Generated by Django 2.2.8 on 2020-02-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20200223_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoicedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invoiced date'),
        ),
    ]
