# Generated by Django 2.2.10 on 2020-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_invoiceddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoicedDate',
            field=models.DateField(blank=True, null=True, verbose_name='Invoiced date'),
        ),
    ]
