# Generated by Django 2.2.10 on 2020-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoiceglobalsettings_firstinvoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchaseOrderNumber',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Purchase order number'),
            preserve_default=False,
        ),
    ]
