# Generated by Django 3.0.7 on 2020-10-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20200302_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceglobalsettings',
            options={'verbose_name': 'Invoice settings', 'verbose_name_plural': 'Invoice settings'},
        ),
    ]
