# Generated by Django 4.2.4 on 2023-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20201024_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='amountPaid',
            field=models.FloatField(verbose_name='Amount paid'),
        ),
    ]
