# Generated by Django 3.1.14 on 2023-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20201024_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='amountPaid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount paid'),
        ),
    ]
