# Generated by Django 2.2.10 on 2020-02-24 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20200224_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceToUser',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Invoice to'),
        ),
    ]
