# Generated by Django 4.2.4 on 2023-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoicepayment_amountpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cache_amountGST_unrounded',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='amountGST_unrounded'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cache_invoiceAmountExclGST_unrounded',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='cache_invoiceAmountExclGST_unrounded'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cache_invoiceAmountInclGST_unrounded',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='cache_invoiceAmountInclGST_unrounded'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cache_totalQuantity',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='cache_totalQuantity'),
        ),
    ]
