# Generated by Django 4.2.4 on 2023-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_cache_amountgst_unrounded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='surchargeAmount',
            field=models.FloatField(default=0, editable=False, verbose_name='Surcharge amount'),
        ),
        migrations.AddField(
            model_name='invoiceglobalsettings',
            name='surchargeAmount',
            field=models.FloatField(default=0, verbose_name='Surcharge amount'),
        ),
        migrations.AddField(
            model_name='invoiceglobalsettings',
            name='surchargeDescription',
            field=models.CharField(default='Surcharge', help_text='This text appears on the invoice.', max_length=50, verbose_name='Surcharge description'),
        ),
    ]
