# Generated by Django 4.2.4 on 2023-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_cache_amountgst_unrounded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceglobalsettings',
            name='surchargeAmount',
            field=models.FloatField(default=0, help_text='Amount excludes GST, GST will be added automatically.', verbose_name='Surcharge amount'),
        ),
        migrations.AddField(
            model_name='invoiceglobalsettings',
            name='surchargeDescription',
            field=models.CharField(blank=True, help_text='Surcharge description appears in small text below the surcharge name.', max_length=70, verbose_name='Surcharge description'),
        ),
        migrations.AddField(
            model_name='invoiceglobalsettings',
            name='surchargeName',
            field=models.CharField(default='Surcharge', help_text='Name of the surcharge on the invoice.', max_length=30, verbose_name='Surcharge name'),
        ),
    ]
