# Generated by Django 2.2.10 on 2020-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20200224_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceNumber',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True, verbose_name='Invoice number'),
            preserve_default=False,
        ),
    ]
