# Generated by Django 4.2.16 on 2024-11-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoiceglobalsettings_surchargeamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceglobalsettings',
            name='surchargeAmount',
            field=models.FloatField(default=0, help_text='Amount includes GST.', verbose_name='Surcharge amount'),
        ),
    ]
