# Generated by Django 2.2.10 on 2020-02-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_invoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceglobalsettings',
            name='invoiceFooterMessage',
            field=models.TextField(default='', verbose_name='Invoice footer message'),
            preserve_default=False,
        ),
    ]
