# Generated by Django 2.2.8 on 2020-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='permissions',
            field=models.CharField(choices=[('viewall', 'View all'), ('eventmanager', 'Event manager'), ('schoolmanager', 'School manager'), ('billingmanager', 'Billing manager'), ('full', 'Full')], max_length=20, verbose_name='Permissions'),
        ),
    ]
