# Generated by Django 2.2.10 on 2020-02-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.State', verbose_name='State'),
        ),
    ]
