# Generated by Django 3.0.3 on 2020-03-14 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200310_2111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordination', '0003_auto_20200226_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.State', verbose_name='State'),
        ),
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together={('user', 'state', 'permissions')},
        ),
    ]
