# Generated by Django 3.0.3 on 2020-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0004_auto_20200314_2124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(condition=models.Q(state=None), fields=('user', 'permissions'), name='user_permissions'),
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(fields=('user', 'state', 'permissions'), name='user_state_permissions'),
        ),
    ]
