# Generated by Django 3.0.7 on 2020-10-15 10:27

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # Normally need to get the model from the versioned app registry;
    # But need to access updateUserPermissions so directly import
    from users.models import User
    for user in User.objects.all():
        user.updateUserPermissions()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0006_auto_20200504_2218'),
        ('users', '0005_user_currentlyselectedadminstate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coordinator',
            name='user_permissions',
        ),
        migrations.RemoveConstraint(
            model_name='coordinator',
            name='user_state_permissions',
        ),
        migrations.RenameField(
            model_name='coordinator',
            old_name='permissions',
            new_name='permissionLevel',
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(condition=models.Q(state=None), fields=('user', 'permissionLevel'), name='user_permissions'),
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(fields=('user', 'state', 'permissionLevel'), name='user_state_permissions'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='permissionLevel',
            field=models.CharField(choices=[('viewall', 'View all'), ('eventmanager', 'Event manager'), ('schoolmanager', 'School manager'), ('billingmanager', 'Billing manager'), ('webeditor', 'Web editor'), ('full', 'Full')], max_length=20, verbose_name='Permission level'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
