# Generated by Django 3.0.7 on 2020-10-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0006_auto_20200504_2218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coordinator',
            name='user_permissions',
        ),
        migrations.RemoveConstraint(
            model_name='coordinator',
            name='user_state_permissions',
        ),
        migrations.RenameField(
            model_name='coordinator',
            old_name='permissions',
            new_name='permissionLevel',
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(condition=models.Q(state=None), fields=('user', 'permissionLevel'), name='user_permissions'),
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(fields=('user', 'state', 'permissionLevel'), name='user_state_permissions'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='permissionLevel',
            field=models.CharField(choices=[('viewall', 'View all'), ('eventmanager', 'Event manager'), ('schoolmanager', 'School manager'), ('billingmanager', 'Billing manager'), ('webeditor', 'Web editor'), ('full', 'Full')], max_length=20, verbose_name='Permission level'),
        ),
    ]
