# Generated by Django 2.2.8 on 2020-02-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20200221_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='bankAccountBSB',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Bank Account BSB'),
        ),
        migrations.AlterField(
            model_name='state',
            name='bankAccountNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Bank Account Number'),
        ),
    ]
