# Generated by Django 3.0.3 on 2020-05-02 12:29

from django.db import migrations, models
import rcjaRegistration.storageBackends
import regions.models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200310_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='defaultEventImage',
            field=models.ImageField(blank=True, null=True, storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_to=regions.models.State.generateUUIDFilename, verbose_name='Default event image'),
        ),
        migrations.AddField(
            model_name='state',
            name='defaultEventImageOriginalFileName',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Original filename'),
        ),
    ]
