# Generated by Django 3.0.3 on 2020-05-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200310_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='treasurer',
        ),
        migrations.AddField(
            model_name='state',
            name='typeGlobal',
            field=models.BooleanField(default=False, help_text='Associate this state with global events.', verbose_name='Global'),
        ),
        migrations.AddField(
            model_name='state',
            name='typeRegistration',
            field=models.BooleanField(default=False, help_text='Use this state in the registration portal. Once enabled cannot be disabled.', verbose_name='Registration'),
        ),
        migrations.AddField(
            model_name='state',
            name='typeWebsite',
            field=models.BooleanField(default=False, help_text='Display this state on the public website.', verbose_name='Website'),
        ),
    ]
