# Generated by Django 2.2.10 on 2020-02-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200222_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='defaultCompDetails',
            new_name='defaultEventDetails',
        ),
    ]
