# Generated by Django 3.0.3 on 2020-05-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200310_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='treasurer',
        ),
    ]
