# Generated by Django 2.2.10 on 2020-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20200225_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=3, unique=True, verbose_name='Abbreviation'),
        ),
    ]
