# Generated by Django 3.0.3 on 2020-05-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20200504_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='typeGlobal',
            field=models.BooleanField(default=False, help_text='Associate this state with global events.', verbose_name='Global'),
        ),
    ]
