# Generated by Django 3.0.7 on 2021-02-09 10:46

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    # Normally need to get the model from the versioned app registry;
    # But need to access updateUserPermissions so directly import
    from users.models import User
    for user in User.objects.all():
        user.updateUserPermissions()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20201014_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global region. Global divisions are only editable by global administrators.', limit_choices_to={'typeRegistration': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='State'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
