# Generated by Django 5.1.15 on 2026-08-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_remove_state_typeregistration_state_typecompetition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='participationDeedText',
            field=models.TextField(blank=True, help_text='Rich text shown to parents when signing an electronic participation deed. HTML is sanitized on display.', verbose_name='Participation deed text'),
        ),
    ]
