# Generated by Django 5.1.5 on 2025-06-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_remove_state_typeregistration_state_typecompetition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='introductionEmailTemplate',
            field=models.TextField(blank=True, default='', help_text="This message is sent to mentors when they sign up. Use {{name}} for where to input the recipient's name and {{events}} for a paragraph that lists events happening soon in your state.", verbose_name='Introduction Email Template'),
        ),
    ]
