# Generated by Django 2.2.10 on 2020-02-26 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('questionText', models.TextField(verbose_name='Question text')),
                ('required', models.BooleanField(default=True, help_text='Users must accept required questions to register', verbose_name='Required')),
            ],
            options={
                'verbose_name': 'Question',
                'ordering': ['-creationDateTime'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('response', models.BooleanField(verbose_name='Response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userquestions.Question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Question Response',
                'ordering': ['question', 'user'],
                'unique_together': {('question', 'user')},
            },
        ),
    ]
