# Generated by Django 2.2.10 on 2020-02-26 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userquestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userquestionresponse',
            name='userQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userquestions.UserQuestion', verbose_name='User question'),
        ),
        migrations.AlterUniqueTogether(
            name='userquestionresponse',
            unique_together={('userQuestion', 'user')},
        ),
    ]
