# Generated by Django 2.2.10 on 2020-02-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquestions', '0002_auto_20200226_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shortTitle',
            field=models.CharField(help_text="This will appear in the admin where the full question text won't fit. Users will never see this.", max_length=20, null=True, unique=True, verbose_name='Short title'),
        ),
    ]
