# Generated by Django 2.2.10 on 2020-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquestions', '0003_question_shorttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='shortTitle',
            field=models.CharField(help_text="This will appear in the admin where the full question text won't fit. Users will never see this.", max_length=20, unique=True, verbose_name='Short title'),
        ),
    ]
