# Generated by Django 2.2.10 on 2020-02-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquestions', '0003_auto_20200226_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-creationDateTime'], 'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='questionresponse',
            options={'ordering': ['question', 'user'], 'verbose_name': 'Question Response'},
        ),
    ]
