# Generated by Django 2.2.10 on 2020-02-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquestions', '0004_auto_20200228_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-required', '-creationDateTime'], 'verbose_name': 'Question'},
        ),
    ]
