# Generated by Django 2.2.10 on 2020-02-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='directEnquiriesTo',
            field=models.ForeignKey(help_text="This person's name and email will appear on the event page", on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Direct enquiries to'),
        ),
        migrations.AddField(
            model_name='event',
            name='divisions',
            field=models.ManyToManyField(through='events.AvailableDivision', to='events.Division', verbose_name='Available divisions'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Year', verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='availabledivision',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Division', verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='availabledivision',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('year', 'state', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='availabledivision',
            unique_together={('event', 'division')},
        ),
    ]
