# Generated by Django 2.2.10 on 2020-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200226_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
    ]
