# Generated by Django 2.2.10 on 2020-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200226_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paymentDueDate',
            field=models.DateField(blank=True, null=True, verbose_name='Payment due date'),
        ),
    ]
