# Generated by Django 2.2.10 on 2020-02-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200221_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='compDetails',
            new_name='eventDetails',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_team_members',
        ),
        migrations.AddField(
            model_name='event',
            name='maxMembersPerTeam',
            field=models.PositiveIntegerField(default=5, verbose_name='Max members per team'),
            preserve_default=False,
        ),
    ]
