# Generated by Django 2.2.10 on 2020-03-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200228_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Division Category',
                'verbose_name_plural': 'Division Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='division',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.DivisionCategory', verbose_name='Category'),
        ),
    ]
