# Generated by Django 2.2.10 on 2020-02-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200225_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('division_maxMembersPerTeam', models.PositiveIntegerField(verbose_name='Max members per team')),
                ('division_maxTeamsPerSchool', models.PositiveIntegerField(blank=True, help_text='Leave blank for no limit. Only enforced in the mentor signup page, can be overridden in the admin portal.', null=True, verbose_name='Max teams per school')),
                ('division_maxTeamsForDivision', models.PositiveIntegerField(blank=True, help_text='Leave blank for no limit. Only enforced in the mentor signup page, can be overridden in the admin portal.', null=True, verbose_name='Max teams for division')),
                ('division_billingType', models.CharField(choices=[('event', 'Event settings'), ('team', 'By team'), ('student', 'By student')], default='event', max_length=15, verbose_name='Billing type')),
                ('division_entryFee', models.PositiveIntegerField(verbose_name='Default entry fee')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Division', verbose_name='Division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Available Division',
                'ordering': ['event', 'division'],
                'unique_together': {('event', 'division')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='availableDivisions',
            field=models.ManyToManyField(through='events.AvailableDivision', to='events.Division', verbose_name='Available divisions'),
        ),
    ]
