# Generated by Django 2.2.10 on 2020-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200225_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additionalInvoiceMessage',
            field=models.TextField(blank=True, help_text='This appears below the state based invoice message on the invoice.', verbose_name='Additional invoice message'),
        ),
    ]
