# Generated by Django 2.2.10 on 2020-02-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200225_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledivision',
            name='division_entryFee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default entry fee'),
        ),
    ]
