# Generated by Django 2.2.10 on 2020-02-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200225_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='availableDivisions',
            new_name='divisions',
        ),
        migrations.AlterField(
            model_name='availabledivision',
            name='division_entryFee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Division entry fee'),
        ),
    ]
