# Generated by Django 2.2.10 on 2020-02-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200225_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_maxMembersPerTeam',
            new_name='maxMembersPerTeam',
        ),
        migrations.RemoveField(
            model_name='availabledivision',
            name='division_maxMembersPerTeam',
        ),
    ]
