# Generated by Django 2.2.10 on 2020-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200225_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maxMembersPerTeam',
            field=models.PositiveIntegerField(help_text='Resets to 0 for workshops', verbose_name='Max members per team'),
        ),
    ]
