# Generated by Django 3.0.3 on 2020-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200315_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='workshopStudentEntryFee',
            field=models.PositiveIntegerField(null=True, verbose_name='Student entry fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='workshopTeacherEntryFee',
            field=models.PositiveIntegerField(null=True, verbose_name='Teacher entry fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_specialRateNumber',
            field=models.PositiveIntegerField(blank=True, help_text='The number of teams specified will be billed at this rate. Subsequent teams will be billed at the default rate. Leave blank for no special rate.', null=True, verbose_name='Special rate number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='maxMembersPerTeam',
            field=models.PositiveIntegerField(default=5, verbose_name='Max members per team'),
        ),
    ]
