# Generated by Django 3.0.3 on 2020-05-02 10:55

from django.db import migrations, models
import events.models
import rcjaRegistration.storageBackends


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200315_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventBannerImage',
            field=models.ImageField(blank=True, null=True, storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_to=events.models.Event.generateUUIDFilename, verbose_name='Banner image'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventBannerImageOriginalFileName',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Original filename'),
        ),
    ]
