# Generated by Django 3.0.3 on 2020-05-02 12:18

from django.db import migrations, models
import events.models
import rcjaRegistration.storageBackends


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200502_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venueImage',
            field=models.ImageField(blank=True, null=True, storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_to=events.models.Venue.generateUUIDFilename, verbose_name='Venue image'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venueImageOriginalFileName',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Original filename'),
        ),
    ]
