# Generated by Django 3.0.7 on 2020-10-07 23:57

from django.db import migrations, models
import events.models
import rcjaRegistration.storageBackends


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200504_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventBannerImage',
            field=models.ImageField(blank=True, null=True, storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_to=events.models.Event.generateUUIDFilename, verbose_name='Banner image'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventBannerImageOriginalFileName',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Original filename'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venueImage',
            field=models.ImageField(blank=True, null=True, storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_to=events.models.Venue.generateUUIDFilename, verbose_name='Venue image'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venueImageOriginalFileName',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Original filename'),
        ),
    ]
