# Generated by Django 3.0.7 on 2020-10-14 04:16

import common.fields
from django.db import migrations, models
import rcjaRegistration.storageBackends


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200504_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventBannerImage',
            field=common.fields.UUIDImageField(blank=True, null=True, original_filename_field='eventBannerImageOriginalFilename', storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_prefix='EventBannerImage', verbose_name='Banner image'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventBannerImageOriginalFilename',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Original filename'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venueImage',
            field=common.fields.UUIDImageField(blank=True, null=True, original_filename_field='venueImageOriginalFilename', storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_prefix='VenueImage', verbose_name='Venue image'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venueImageOriginalFilename',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Original filename'),
        ),
    ]
