# Generated by Django 3.0.7 on 2020-10-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20201014_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Division'},
        ),
    ]
