# Generated by Django 3.0.7 on 2020-10-10 01:24

import common.fields
from django.db import migrations
import rcjaRegistration.storageBackends


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20201010_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventBannerImage',
            field=common.fields.UUIDImageField(blank=True, null=True, storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_to=common.fields.UUIDFIeld.generateUUIDFilename, verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venueImage',
            field=common.fields.UUIDImageField(blank=True, null=True, storage=rcjaRegistration.storageBackends.PublicMediaStorage(), upload_to=common.fields.UUIDFIeld.generateUUIDFilename, verbose_name='Venue image'),
        ),
    ]
