# Generated by Django 3.1.6 on 2021-05-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_year_displayeventsonwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseeventattendance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
