# Generated by Django 3.1.14 on 2023-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_baseeventattendance_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maxMembersPerTeam',
            field=models.PositiveIntegerField(default=4, verbose_name='Max members per team'),
        ),
    ]
