# Generated by Django 4.2.4 on 2023-09-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_remove_state_typeregistration_state_typecompetition_and_more'),
        ('events', '0018_auto_20230901_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global division. Global divisions are only editable by global administrators.', limit_choices_to={'typeCompetition': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.ForeignKey(limit_choices_to={'typeCompetition': True}, on_delete=django.db.models.deletion.PROTECT, to='regions.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.ForeignKey(limit_choices_to={'typeCompetition': True}, on_delete=django.db.models.deletion.PROTECT, to='regions.state', verbose_name='State'),
        ),
    ]
