# Generated by Django 4.2.16 on 2024-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_eventsurchargeamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
