# Generated by Django 4.2.16 on 2025-01-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_division_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledivision',
            name='division',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='events.division', verbose_name='Division'),
        ),
    ]
