# Generated by Django 4.2.16 on 2025-01-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_availabledivision_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='Event end date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_defaultEntryFee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default entry fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registrationsCloseDate',
            field=models.DateField(blank=True, null=True, verbose_name='Registration close date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registrationsOpenDate',
            field=models.DateField(blank=True, null=True, verbose_name='Registrations open date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Event start date'),
        ),
    ]
