# Generated by Django 4.2.16 on 2025-01-09 11:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_availabledivision_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cmsEventId',
            field=models.CharField(editable=False, help_text='The ID of this event in the RCJ CMS', max_length=15, null=True, verbose_name='CMS Event ID'),
        )
    ]
