# Generated by Django 4.2.16 on 2025-01-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_event_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_billingType',
            new_name='competition_billingType',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_defaultEntryFee',
            new_name='competition_defaultEntryFee',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_specialRateFee',
            new_name='competition_specialRateFee',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_specialRateNumber',
            new_name='competition_specialRateNumber',
        ),
    ]
