# Generated by Django 4.2.18 on 2025-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_rename_event_billingtype_event_competition_billingtype_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_type_check',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('eventType', 'workshop'), ('eventType', 'competition'), _connector='OR'), name='eventType_check'),
        ),
    ]
