# Generated by Django 4.2.18 on 2025-01-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoiceglobalsettings_surchargeamount'),
        ('events', '0027_event_cmseventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseeventattendance',
            name='invoiceOverride',
            field=models.ForeignKey(blank=True, help_text='Select an invoice to bill this team/ attendee to instead of the default behaviour.', null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.invoice', verbose_name='Invoice override'),
        ),
    ]
