# Generated by Django 5.1.5 on 2025-01-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_baseeventattendance_invoiceoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledivision',
            name='division',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='events.division', verbose_name='Division'),
        ),
    ]
