# Generated by Django 5.1.15 on 2026-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_rename_division_maxteamsfordivision_availabledivision_division_maxregistrationsfordivision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseeventattendance',
            name='csv_imported',
            field=models.BooleanField(default=False, editable=False, verbose_name='CSV imported'),
        ),
    ]
