# Generated by Django 5.1.5 on 2025-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_rename_division_maxteamsfordivision_availabledivision_division_maxregistrationsfordivision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='showPizzaPreference',
            field=models.BooleanField(default=False, help_text='If enabled, workshop attendees will see a pizza preference field during registration.', verbose_name='Show pizza preference field'),
        ),
    ]
