# Generated by Django 5.1.15 on 2026-08-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_baseeventattendance_csv_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='electronicParticipationDeedsEnabled',
            field=models.BooleanField(default=False, help_text='Allow parents to sign participation deeds electronically for this event.', verbose_name='Participation deeds'),
        ),
    ]
