# Generated by Django 3.0.3 on 2020-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopattendee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='workshopattendee',
            name='yearLevel',
            field=models.CharField(max_length=10, verbose_name='Year level'),
        ),
    ]
