# Generated by Django 3.1.14 on 2023-08-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20200501_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopattendee',
            name='birthday',
        ),
    ]
