# Generated by Django 4.2.4 on 2023-09-08 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_remove_workshopattendee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopattendee',
            name='firstName',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_ and space.", regex='^[0-9a-zA-Z \\-\\_]*$')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='workshopattendee',
            name='lastName',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_ and space.", regex='^[0-9a-zA-Z \\-\\_]*$')], verbose_name='Last name'),
        ),
    ]
