# Generated by Django 5.1.5 on 2025-08-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_workshopattendee_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopattendee',
            name='pizzaPreference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pizza preference'),
        ),
    ]
