# Generated by Django 5.1.15 on 2026-08-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participationdeeds', '0001_participation_deeds'),
        ('workshops', '0005_alter_workshopattendee_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopattendee',
            name='participationDeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participationdeeds.participationdeed', verbose_name='Participation deed'),
        ),
    ]
