# Generated by Django 2.2.8 on 2020-02-21 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=5, unique=True, verbose_name='Abbreviation')),
                ('joinKey', models.CharField(blank=True, max_length=10, verbose_name='Join key')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.Region', verbose_name='Region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='State')),
            ],
            options={
                'verbose_name': 'School',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School', verbose_name='School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mentor',
                'ordering': ['user'],
            },
        ),
    ]
