# Generated by Django 2.2.10 on 2020-02-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
            ],
            options={
                'verbose_name': 'School administrator',
                'ordering': ['user'],
            },
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='school',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
    ]
