# Generated by Django 2.2.10 on 2020-02-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0002_state_treasurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='campus',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School', verbose_name='School'),
        ),
        migrations.AlterUniqueTogether(
            name='schooladministrator',
            unique_together={('school', 'user')},
        ),
    ]
