# Generated by Django 2.2.8 on 2020-02-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='joinKey',
            field=models.CharField(blank=True, max_length=10, verbose_name='Join key'),
        ),
    ]
