# Generated by Django 2.2.8 on 2020-02-21 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_joinkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='mobileNumber',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
