# Generated by Django 2.2.10 on 2020-02-23 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorquestions', '0003_auto_20200224_0003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0002_auto_20200224_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.AddField(
            model_name='schooladministrator',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='schooladministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
