# Generated by Django 2.2.10 on 2020-02-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20200226_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='forceSchoolDetailsUpdate',
            field=models.BooleanField(default=False, verbose_name='Force details update'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='State'),
        ),
    ]
