# Generated by Django 2.2.10 on 2020-02-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0003_auto_20200224_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='joinKey',
        ),
        migrations.AlterUniqueTogether(
            name='schooladministrator',
            unique_together={('school', 'user')},
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Campus',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.AddField(
            model_name='schooladministrator',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Campus', verbose_name='Campus'),
        ),
    ]
