# Generated by Django 3.0.3 on 2020-05-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20200505_1353'),
        ('schools', '0004_auto_20200501_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.ForeignKey(limit_choices_to={'typeRegistration': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.State', verbose_name='State'),
        ),
    ]
