# Generated by Django 3.0.7 on 2020-10-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20200504_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('school', 'name')},
        ),
    ]
