# Generated by Django 2.2.10 on 2020-02-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20200224_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(help_text='Abbreviation is used in the schedule and scoring system', max_length=5, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='regions.Region', verbose_name='Region'),
            preserve_default=False,
        ),
    ]
