# Generated by Django 4.2.4 on 2023-09-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_remove_state_typeregistration_state_typecompetition_and_more'),
        ('schools', '0006_auto_20201016_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.ForeignKey(limit_choices_to={'typeUserRegistration': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.state', verbose_name='State'),
        ),
    ]
