# Generated by Django 5.1.5 on 2025-01-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_campus_name_alter_campus_postcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='abbreviation',
        ),
    ]
