# Generated by Django 4.2.16 on 2024-11-03 04:39

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('address', models.TextField(blank=True, verbose_name='Residential address')),
                ('membershipStartDate', models.DateField(blank=True, null=True, verbose_name='Membership start date')),
                ('membershipEndDate', models.DateField(blank=True, null=True, verbose_name='Membership end date')),
                ('lifeMemberAwardedDate', models.DateField(blank=True, null=True, verbose_name='Life membership awarded date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Association Member',
                'ordering': ['user'],
            },
            bases=(common.models.SaveDeleteMixin, models.Model),
        ),
    ]
