# Generated by Django 5.1.5 on 2025-01-26 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmember',
            name='approvalDate',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Approval date'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='approvalStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='approvedBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvedBy', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='rulesAcceptedDate',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Rules accepted date'),
        ),
    ]
