# Generated by Django 5.1.5 on 2025-01-31 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_associationmember_approvalrejectionby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmember',
            name='approvalRejectionBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associationMemberApprovalRejections', to=settings.AUTH_USER_MODEL, verbose_name='Approved/ rejected by'),
        ),
    ]
