# Generated by Django 5.2.17 on 2026-10-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_alter_associationmember_approvalrejectionby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmember',
            name='rulesAcceptedDate',
            field=models.DateField(blank=True, null=True, verbose_name='Rules accepted date'),
        ),
    ]
