# Generated by Django 2.2.10 on 2020-02-26 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0002_auto_20200226_1204'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mentorUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Mentor'),
        ),
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.School', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='Team'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('event', 'name')},
        ),
    ]
