# Generated by Django 3.0.3 on 2020-03-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200226_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team'
        ),
        migrations.DeleteModel(
            name='student'
        ),   
    ]
