# Generated by Django 3.0.3 on 2020-03-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_student_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwarePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hardware Platform',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwarePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Software Platform',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='hardwarePlatform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.HardwarePlatform', verbose_name='Hardware platform'),
        ),
        migrations.AddField(
            model_name='team',
            name='softwarePlatform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.SoftwarePlatform', verbose_name='Software platform'),
        ),
    ]
