# Generated by Django 4.2.4 on 2023-09-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_student_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='overrideEventLimits',
            field=models.BooleanField(default=False, editable=False, verbose_name='Override event limits'),
        ),
    ]
