# Generated by Django 4.2.4 on 2023-09-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_student_firstname_alter_student_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Platform Category',
                'verbose_name_plural': 'Platform Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.platformcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='softwareplatform',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.platformcategory', verbose_name='Category'),
        ),
    ]
