# Generated by Django 5.1.7 on 2026-01-16 01:11

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '__first__'),
        ('teams', '0010_team_withdrawn'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studenta', verbose_name='Student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Student',
                'ordering': ['team', 'student'],
            },
            bases=(common.models.SaveDeleteMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
