# Generated by Django 5.1.15 on 2026-07-06 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_team_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_' and space.", regex="^[0-9a-zA-Z \\-\\_']*$")], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_' and space.", regex="^[0-9a-zA-Z \\-\\_']*$")], verbose_name='Last name'),
        ),
    ]
