# Generated by Django 5.1.7 on 2026-02-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_person_remove_studenta_school_student'),
        ('teams', '0011_teamparticipation_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['event', 'division', 'name'], 'verbose_name': 'Team'},
        ),
        migrations.AlterField(
            model_name='teamparticipation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student'),
        ),
    ]
