# Generated by Django 5.1.15 on 2026-08-24 14:37

import common.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0031_participation_deeds'),
        ('schools', '0009_remove_school_abbreviation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationDeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('parentName', models.CharField(max_length=100, verbose_name='Parent name')),
                ('signedDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Signed date/time')),
                ('submittedFirstName', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_' and space.", regex="^[0-9a-zA-Z \\-\\_']*$")], verbose_name='Submitted first name')),
                ('submittedLastName', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_' and space.", regex="^[0-9a-zA-Z \\-\\_']*$")], verbose_name='Submitted last name')),
                ('submittedYearLevel', models.PositiveIntegerField(verbose_name='Submitted year level')),
                ('mentorUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
                ('originalEvent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Original event')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Participation deed',
                'ordering': ['-signedDateTime'],
            },
            bases=(common.models.SaveDeleteMixin, models.Model),
        ),
    ]
