# Generated by Django 5.1.15 on 2026-08-26 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participationdeeds', '0001_participation_deeds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participationdeed',
            name='ipAddress',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='participationdeed',
            name='loggedInUser',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Logged in user'),
        ),
        migrations.AddField(
            model_name='participationdeed',
            name='userAgent',
            field=models.TextField(blank=True, editable=False, verbose_name='User agent'),
        ),
    ]
