# Generated by Django 5.1.7 on 2026-02-17 07:14

import common.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0009_remove_school_abbreviation"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_ and space.",
                                regex="^[0-9a-zA-Z \\-\\_]*$",
                            )
                        ],
                        verbose_name="First name",
                    ),
                ),
                (
                    "lastName",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Contains character that isn't allowed. Allowed characters are a-z, A-Z, 0-9, -_ and space.",
                                regex="^[0-9a-zA-Z \\-\\_]*$",
                            )
                        ],
                        verbose_name="Last name",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schools.campus",
                        verbose_name="Campus",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            bases=(common.models.SaveDeleteMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="studenta",
            name="school",
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="students.person",
                    ),
                ),
                (
                    "graduationYear",
                    models.PositiveIntegerField(verbose_name="Year 12 Graduation Year"),
                ),
            ],
            options={
                "verbose_name": "Student",
                "ordering": ["school", "lastName", "firstName"],
            },
            bases=("students.person",),
        ),
    ]
