# Generated by Django 5.1.7 on 2026-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_delete_studenta_student_mentoruser"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="archive",
            field=models.BooleanField(default=False),
        ),
    ]
