# Generated by Django 3.0.3 on 2020-05-04 12:18

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0004_auto_20200505_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updatedDateTime', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.State', verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Committee member',
                'ordering': ['state', 'user'],
            },
            bases=(common.models.SaveDeleteMixin, models.Model),
        ),
    ]
